interface unwind-pnl-handler {
    use jabratech:common/types.{response-error};
    use types.{unwind-pnl-response};
    get: func (user-email: string) -> result<unwind-pnl-response, response-error>;
}